language: node_js
node_js: 
  - "8.9.3"

branches:
  only:
    - master
    - staging

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    gihutb_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master